language: go

go:
  - "1.10"

addons:
  apt:
    packages:
      - docker-ce

script:
  - cd code
  - CGO_ENABLED=0 go build
  - cd ..
  - docker build --rm -t trigun117/grabber .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push trigun117/grabber