sudo: required

language: go

go:
  - "1.10"

addons:
  apt:
    packages:
      - docker-ce

script:
  - cd code
  - CGO_ENABLED=0 go build
  - cd ..
  - docker build --rm -t trigun117/grabber .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push trigun117/grabber